# Generated by Django 4.2.6 on 2023-10-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_group_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
